apiVersion: external-secrets.io/v1beta1
kind: SecretStore # You could also choose ClusterSecretStore 
metadata:
  name: secret-store-vault
  namespace: external-secret
spec:
  provider:
    vault:
      server: "https://vault.vault-database-engine.vkpr.platform.vee.codes" #the address of your vault instance
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2".
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"