name: infracost estimate

on:
  workflow_dispatch: 
env:
  PATH_INFRACOST: ./.platform

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: hashicorp/setup-terraform@v2

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Import AWS Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.apr.vee.codes
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              aws/creds/vaultAction access_key | AWS_ACCESS_KEY_ID ;
              aws/creds/vaultAction secret_key | AWS_SECRET_ACCESS_KEY ; 
              
      - name: Import Github Secrets Secret
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.apr.vee.codes
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              secrets/data/environment-vault-impl-ref/actions/GH_USERNAME value | GH_USERNAME ;          
              secrets/data/environment-vault-impl-ref/actions/GH_EMAIL value | GH_EMAIL ;
              secrets/data/environment-vault-impl-ref/actions/INFRACOST_API_KEY value | INFRACOST_API_KEY ;
                              
      - run: sleep 10
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:  ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ env.INFRACOST_API_KEY }}
          path: |
            .terraform/**
            .terraform.lock.hcl
            plan_cache.json
          key: terraform-lock-${{ steps.extract_branch.outputs.branch }}

      - name: Terraform Init
        id: init
        run: |
             terraform init
             terraform plan -no-color -out plan_cache.json 
      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --show-skipped --path plan_cache.json

      - name: Generate Infracost cost estimate Json
        run: |
          infracost breakdown --path plan_cache.json --format json --out-file ${{ env.PATH_INFRACOST }}/infracost-base.json

      - name: Generate component infracost.yaml
        run: |
          echo 'apiVersion: veecode.backstage.io/v1alpha1
          kind: Infracost
          metadata:
            name: cluster-vault-impl-ref
            annotations:
             backstage.io/techdocs-ref: dir:.
          spec:
            type: FinOps
            lifecycle: experimental
            owner: "group:default/admin"
            estimate:
             $text: ./infracost-base.json' > ${{ env.PATH_INFRACOST }}/infracost.yaml

      - name: Publish generated artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "${{ env.PATH_INFRACOST }}"
          commit_user_name: ${{ env.GH_USERNAME }}
          commit_user_email: ${{ env.GH_EMAIL }}
          commit_author: ${{ env.GH_USERNAME }}<${{ env.GH_EMAIL }}>
          commit_message: "Publish infracost estimate"
          push_options: '--force'