name: Stop Instance

on:
  workflow_dispatch:
env:
  PORT: 6550
  USERNAME: ec2-user   
jobs:
  Stop_Instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2        
      - name: Import AWS Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.apr.vee.codes
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              aws/creds/vaultAction access_key | AWS_ACCESS_KEY_ID ;
              aws/creds/vaultAction secret_key | AWS_SECRET_ACCESS_KEY ; 
      - run: sleep 10
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:  ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Stop Instance
        run: |
          ID_INSTANCE=`aws ec2 describe-instances --filters "Name=tag-key,Values=Name" "Name=tag-value,Values=cluster-vault-impl-ref" --query "Reservations[*].Instances[*].InstanceId" --output text`
          echo "Stop Instance cluster-vault-impl-ref"
          aws ec2 stop-instances --instance-ids $ID_INSTANCE

